version : "3.9"
services:
  wordpress:
    container_name: wordpress_
    build: ./requirements/wordpress
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - docker-network
    volumes:
      - wp_vl:/var/www/html
      
  nginx:
    container_name: nginx_
    build: ./requirements/nginx
    depends_on:
      - wordpress
    networks:
      - docker-network
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - "wp_vl:/var/www/html"

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - docker-network
    volumes:
      - db_vl:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "$MARIADB_USER", "-p$MARIADB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  docker-network:

volumes:
  db_vl:
    driver: local
    driver_opts:
      device: /home/charli/data/db
      type: volume
      o: bind
  wp_vl:
    driver: local
    driver_opts:
      device: /home/charli/data/wp
      type: volume
      o: bind
